spring:
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/store
    username: store
    password: 123456